name: Publish to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [new-url]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Fetch existing gh-pages content
        run: |
          # Create entries directory if it doesn't exist
          mkdir -p entries
          
          # Fetch existing content from gh-pages branch
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "Fetching existing content from gh-pages..."
            git fetch origin gh-pages
            git worktree add temp-gh-pages origin/gh-pages
            
            # Copy existing entries to current directory
            if [ -d "temp-gh-pages/entries" ]; then
              cp -r temp-gh-pages/entries/* entries/ 2>/dev/null || echo "No existing entries found"
              echo "Copied existing entries to working directory"
            fi
            
            # Clean up worktree
            git worktree remove temp-gh-pages
          else
            echo "No existing gh-pages branch found, starting fresh"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Extract and write article
        run: |
          echo '${{ toJson(github.event) }}' > payload.json
          python extract.py

      - name: Prepare site folder
        run: |
          mkdir site
          cp index.html site/
          cp -r entries site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          keep_files: false
