name: Publish to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [new-url]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Extract and write article
        run: |
          echo '${{ toJson(github.event) }}' > payload.json
          python extract.py
          
      - name: Pull existing gh-pages content
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages origin/gh-pages
          cp -r gh-pages/* site/ || true
          git worktree remove gh-pages

      - name: Copy site files
        run: |
          mkdir site
          cp index.html site/
          cp -r entries site/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
