name: Save Article Metadata

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [new-url]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Extract and write article
        run: |
          echo '${{ toJson(github.event) }}' > payload.json
          python extract.py

      - name: Prepare site folder
        run: |
          mkdir site
          cp metadata.json site/ 2>/dev/null || echo "No metadata file found"
          echo "gitpocket.saeedm.com" > site/CNAME

      - name: Commit and push metadata.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add metadata.json
          git commit -m "Update metadata.json [skip ci]" || echo "No changes to commit"
          git push origin main
