name: Publish to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [new-url]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || echo "No gh-pages branch found"
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            mkdir -p entries
            cp -r entries/* temp_entries/ 2>/dev/null || echo "No existing entries"
            cp index.html temp_index.html 2>/dev/null || echo "No existing index"
            git checkout main
            mkdir -p entries
            cp -r temp_entries/* entries/ 2>/dev/null || echo "No temp entries to restore"
            cp temp_index.html index.html 2>/dev/null || echo "No temp index to restore"
            rm -rf temp_entries temp_index.html 2>/dev/null || true
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Extract and write article
        run: |
          echo '${{ toJson(github.event) }}' > payload.json
          python extract.py
          
      - name: Copy site files
        run: |
          mkdir site
          cp index.html site/
          cp -r entries site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
